server:
  port: 8090

spring:
  application:
    name: ms-vidasalud-bff

  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${AZURE_TENANT_ID:245aec22-d743-4c13-a6e6-dce0a19bc1cf}
        credential:
          client-id: ${AZURE_CLIENT_ID:fd189494-2ea3-4c54-91ed-5b5ddd644163}
        app-id-uri: ${AZURE_APP_ID_URI:api://fd189494-2ea3-4c54-91ed-5b5ddd644163}

vidasalud:
  services:
    appointments-url: ${APPOINTMENTS_URL:http://localhost:8090}
    catalog-url: ${CATALOG_URL:http://localhost:8091}
